initial

diff --git a/server/makefile b/server/makefile
--- a/server/makefile
+++ b/server/makefile
@@ -1,58 +1,118 @@
 include .env
 
-# Makefile for building and running the Docker image and container
-.PHONY: run live build db stop cleanI cleanC exec test generate
+PACKAGES := $(shell go list ./...)
+BASENAME := $(shell basename ${PWD})
+
+.PHONY: run live build db hasura redis stop cleanI cleanC exec test help
 .DEFAULT_GOAL:= run
 
-# Build the Docker image and run the container
-run: cleanC generate build
-	docker run -d --name $(APP_NAME) -p $(PORT):$(PORT) --env-file .env $(APP_NAME)
+help: makefile
+	@echo
+	@echo " Choose a make command to run"
+	@echo
+	@sed -n 's/^##//p' $< | column -t -s ':' |  sed -e 's/^/ /'
+	@echo
 
-live: generate
-#	find . -type f \( -name '*.go' -o -name '*.templ' \) | entr -r sh -c 'make && docker logs --follow $(APP_NAME)'
-	find . -type f \( -name '*.go' -o -name '*.templ' \) | entr -r sh -c 'go build -o /tmp/build ./cmd && /tmp/build'
+## run: Build the Docker image and run the container
+run: cleanC create_network connect build
+	docker run -d \
+		--env-file .env \
+		--restart always \
+		--name $(APP_NAME) \
+		--network $(APP_NAME) \
+		-p $(APP_PORT):$(APP_PORT) \
+		$(APP_NAME)
 
-# Build the Docker image
+## live: Go build and running
+live:
+#	find . -type f \( -name '*.go' \) | entr -r sh -c 'make && docker logs --follow $(APP_NAME)'
+	find . -type f \( -name '*.go' \) | entr -r sh -c 'go build -o /tmp/build ./cmd && /tmp/build'
+
+## build: Build the Docker image
 build:
 	docker build -t $(APP_NAME) .
 
-# Postgres
-db:
-	docker volume create $(APP_NAME)-postgres
-	docker run --name $(APP_NAME)-postgres \
+connect:
+ifeq ($(APP_ENV),prod)
+	$(MAKE) db
+	$(MAKE) redis
+	$(MAKE) hasura
+endif
+
+## db: Run Postgres
+db: create_volume
+	docker run -d --name $(APP_NAME)-postgres --restart always \
 		-p $(DB_PORT):5432  \
+		-e TZ="Europe/Istanbul" \
 		-e POSTGRES_DB=$(DB_NAME) \
+		-e POSTGRES_USER=$(DB_USER) \
 		-e POSTGRES_PASSWORD=$(DB_PASS) \
-		-v $(APP_NAME)-postgres:/var/lib/postgresql/data -d \
+		-v $(APP_NAME):/var/lib/postgresql/data \
+		--network $(APP_NAME) \
 		postgres
 
-# Stop and remove the Docker container
-# --time=600 for waiting running job
+## hasura: Run Hasura
+hasura:
+	docker run -d --name $(APP_NAME)-hasura --restart always \
+		-p $(HASURA_PORT):$(HASURA_PORT) \
+		-e HASURA_GRAPHQL_DATABASE_URL="postgres://$(DB_USER):$(DB_PASS)@flowize-postgres:$(DB_PORT)/$(DB_NAME)" \
+		-e HASURA_GRAPHQL_ENABLED_LOG_TYPES="startup, http-log, webhook-log, websocket-log, query-log" \
+		-e HASURA_GRAPHQL_ENABLE_CONSOLE="true" \
+		-e HASURA_GRAPHQL_ADMIN_SECRET=$(HASURA_ADMIN_SECRET) \
+		-e HASURA_GRAPHQL_JWT_SECRET='{"type":"HS256","key":"$(JWT_SECRET)"}' \
+		-v $(APP_NAME):/hasura-migrations \
+		--network $(APP_NAME) \
+		hasura/graphql-engine:v2.9.0
+
+## redis: Run Redis
+redis:
+	docker run -d --name $(APP_NAME)-redis -p 6379:6379 --restart always --network $(APP_NAME) redis:latest
+
+## create_network: Create network for this project name
+create_network:
+	@if ! docker network inspect $(APP_NAME) >/dev/null 2>&1; then \
+		docker network create $(APP_NAME); \
+	else \
+		echo "Network '$(APP_NAME)' already exists, using existing network."; \
+	fi
+
+## create_volume: Create volume for this project name
+create_volume:
+	@if ! docker volume inspect $(APP_NAME) >/dev/null 2>&1; then \
+		docker volume create $(APP_NAME); \
+	else \
+		echo "Volume '$(APP_NAME)' already exists, skipping creation."; \
+	fi
+
+## stop: Stop and remove the Docker container 
 stop:
 	docker stop --time=600 $(APP_NAME)
 	docker rm $(APP_NAME)
 
-# Run the application inside the Docker container
+## exec: Run the application inside the Docker container
 exec:
-	docker exec -it $(APP_NAME) bash
+	docker exec -it $(APP_NAME) $(CMD)
 
-# Clean up the Docker image
+## cleanI: Clean up the Docker image
 cleanI:
 	docker rmi $(APP_NAME)
 	docker builder prune --filter="image=$(APP_NAME)"
 
+## cleanC: Clean up the Docker containers
 cleanC:
 	@CONTAINER_EXISTS=$$(docker ps -aq --filter name=$(APP_NAME)); \
 	if [ -n "$$CONTAINER_EXISTS" ]; then \
-		echo "Stopping and removing container $(APP_NAME)"; \
-		docker stop $(APP_NAME); \
-		docker rm $(APP_NAME); \
+		echo "Stopping and removing containers starting with $(APP_NAME)"; \
+		CONTAINERS=$$(docker ps -aq --filter name=$(APP_NAME)); \
+		for container in $$CONTAINERS; do \
+			echo "Stopping and removing container $$container"; \
+			docker stop $$container; \
+			docker rm $$container; \
+		done; \
 	else \
-		echo "No such container: $(APP_NAME)"; \
+		echo "No such containers starting with: $(APP_NAME)"; \
 	fi
 
+## test: Run all test
 test: 
 	go test -v ./...
-
-generate:
-	templ generate
